version: 2
updates:
  - package-ecosystem: gomod
    directory: /
    schedule:
      interval: daily
    target-branch: develop
  - package-ecosystem: "gitsubmodule"
    directory: "/"
    schedule:
      interval: daily
    target-branch: develop
  - package-ecosystem: gomod
    directory: /
    schedule:
      interval: daily
    target-branch: v2
  - package-ecosystem: "gitsubmodule"
    directory: "/"
    schedule:
      interval: daily
    target-branch: v2
